Repository mdn/interactive-examples, pull requests merged in 2018-04, with the labels that each got.

#691 Fix issue #690, add output label to tabbed editor output pane
  css/tabbed-editor.css
  tmpl/live-tabbed-tmpl.html
Labels: P1, enhancement

#696 Further tweaks to HTML editor UI
  css/editor-libs/tabby.css
  css/tabbed-editor.css
Labels: P1, enhancement

#652 Apply code in code block instead of choice element
  js/editor-libs/css-editor-utils.js
Labels: bug, enhancement

#719 Tabbed editor wrap long lines
  js/editor-libs/tabby.js
Labels: P1, enhancement

#727 fix: update to tabbed editor ui
  css/editor-libs/tabby.css
  css/tabbed-editor.css
Labels: P2, enhancement

#756 Add <kbd> example
  live-examples/html-examples/inline-text-semantics/css/kbd.css
  live-examples/html-examples/inline-text-semantics/kbd.html
  live-examples/html-examples/inline-text-semantics/meta.json
Labels: P1, in sprint

#777 fix: issue #774, escape < in page titles
  CONTRIBUTING-HTML.md
  lib/pageBuilderUtils.js
  live-examples/html-examples/content-sectioning/meta.json
  live-examples/html-examples/forms/meta.json
  live-examples/html-examples/image-and-multimedia/meta.json
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/table-content/meta.json
  live-examples/html-examples/text-content/meta.json
Labels: P1, bug, enhancement, in sprint

#775 Add <mark> example
  live-examples/html-examples/inline-text-semantics/css/mark.css
  live-examples/html-examples/inline-text-semantics/mark.html
  live-examples/html-examples/inline-text-semantics/meta.json
Labels: P1, in sprint

#793 adding form element example
  live-examples/html-examples/forms/css/form.css
  live-examples/html-examples/forms/form.html
  live-examples/html-examples/forms/meta.json
Labels: P1, in sprint

#796 Add <dfn> example
  live-examples/html-examples/inline-text-semantics/css/dfn.css
  live-examples/html-examples/inline-text-semantics/dfn.html
  live-examples/html-examples/inline-text-semantics/meta.json
Labels: P1, in sprint

#805 chore: Adds prettier, prettier-eslint and prettier-stylelint as dev dependencies
  package-lock.json
  package.json
Labels: enhancement, tooling

#799 Add <data> example
  live-examples/html-examples/inline-text-semantics/css/data.css
  live-examples/html-examples/inline-text-semantics/data.html
  live-examples/html-examples/inline-text-semantics/meta.json
Labels: P1, in sprint

#791 Add <sub> example
  live-examples/html-examples/inline-text-semantics/css/sub.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/sub.html
Labels: P1, in sprint

#790 Add <u> example
  live-examples/html-examples/inline-text-semantics/css/u.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/u.html
Labels: P1, in sprint

#806 chore: Small change to output line-height
  css/tabbed-editor.css
Labels: enhancement

#792 Add <sup> example
  live-examples/html-examples/inline-text-semantics/css/sup.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/sup.html
Labels: P1, in sprint

#807 fix: Broken meta.json due to bad merge
  live-examples/html-examples/inline-text-semantics/meta.json
Labels: bug

#812 Add <i> example
  live-examples/html-examples/inline-text-semantics/css/i.css
  live-examples/html-examples/inline-text-semantics/i.html
  live-examples/html-examples/inline-text-semantics/meta.json
Labels: P1, in sprint

#776 adding live example for the button element
  live-examples/html-examples/forms/button.html
  live-examples/html-examples/forms/css/button.css
  live-examples/html-examples/forms/meta.json
Labels: P1, in sprint

#794 adding label element example
  live-examples/html-examples/forms/css/label.css
  live-examples/html-examples/forms/label.html
  live-examples/html-examples/forms/meta.json
Labels: P1, in sprint

#798 adding meter element example
  live-examples/html-examples/forms/css/meter.css
  live-examples/html-examples/forms/meta.json
  live-examples/html-examples/forms/meter.html
Labels: P1, in sprint

#801 adding progress element example
  live-examples/html-examples/forms/css/progress.css
  live-examples/html-examples/forms/meta.json
  live-examples/html-examples/forms/progress.html
Labels: P1, in sprint

#797 Add <q> example
  live-examples/html-examples/inline-text-semantics/css/q.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/q.html
Labels: P1, in sprint

#803 Add <cite> example
  live-examples/html-examples/inline-text-semantics/cite.html
  live-examples/html-examples/inline-text-semantics/css/cite.css
  live-examples/html-examples/inline-text-semantics/meta.json
Labels: P1, in sprint

#808 Add <code> example
  live-examples/html-examples/inline-text-semantics/code.html
  live-examples/html-examples/inline-text-semantics/css/code.css
  live-examples/html-examples/inline-text-semantics/meta.json
Labels: P1, in sprint

#810 Add <em> example
  live-examples/html-examples/inline-text-semantics/css/em.css
  live-examples/html-examples/inline-text-semantics/em.html
  live-examples/html-examples/inline-text-semantics/meta.json
Labels: P1, in sprint

#813 Add <s> example
  live-examples/html-examples/inline-text-semantics/css/s.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/s.html
Labels: P1, in sprint

#827 chore: adds @2alin as contributor
  .all-contributorsrc
  README.md
Labels: community

#814 Add <samp> example
  live-examples/html-examples/inline-text-semantics/css/samp.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/samp.html
Labels: P1, in sprint

#826 Add interactive example for dl element
  live-examples/html-examples/text-content/css/dl.css
  live-examples/html-examples/text-content/dl.html
  live-examples/html-examples/text-content/meta.json
Labels: P1, example needed, in sprint

#819 Add <small> example
  live-examples/html-examples/inline-text-semantics/css/small.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/small.html
Labels: P1, in sprint

#789 Issue #730 - Content Sectioning - header
  live-examples/html-examples/content-sectioning/css/header.css
  live-examples/html-examples/content-sectioning/header.html
  live-examples/html-examples/content-sectioning/meta.json
  media/examples/DancingScript-Regular.ttf
  media/examples/puppy-header-logo.jpg
Labels: P1, in sprint

#809 adding textarea element example
  live-examples/html-examples/forms/css/textarea.css
  live-examples/html-examples/forms/meta.json
  live-examples/html-examples/forms/textarea.html
Labels: P1, in sprint
