Repository mdn/interactive-examples, pull requests merged in 2018-07, with the labels that each got.

#1010 fix(performance): only send loading mark inside loading event
  js/editor-libs/perf.js
Labels: bug

#1011 Send metric only during loading event
  js/editor-libs/perf.js
Labels: bug

#1009 Issue#946 open links in new tab
  js/editor-libs/mce-utils.js
  js/editor.js
Labels: community

#1017 Issue #1013 <style> elements in HTML editor break editor's render method
  js/editor.js
Labels: P1, bug, community

#1018 chore(community): add @ro-ka as contributor
  .all-contributorsrc
  README.md
Labels: community

#1019 chore(community): add @arai-a as contributor
  .all-contributorsrc
  README.md
Labels: community

#1008 Add color-adjust property example
  live-examples/css-examples/color/color-adjust.css
  live-examples/css-examples/color/color-adjust.html
  live-examples/css-examples/color/meta.json
Labels: example needed

#1024 html/input: Lowercase attributes
  live-examples/html-examples/input/password.html
  live-examples/html-examples/input/text.html
Labels: bug, community

#1015 fix(tabbed): load fonts as part of the editor css as @font-face does not work inside shadow dom
  CONTRIBUTING-HTML.md
  css/editor-libs/shadow-fonts.css
  live-examples/html-examples/content-sectioning/css/article.css
  live-examples/html-examples/content-sectioning/css/aside.css
  live-examples/html-examples/content-sectioning/css/header.css
  live-examples/html-examples/document-metadata/css/style.css
  live-examples/html-examples/document-metadata/style.html
  live-examples/html-examples/forms/css/fieldset.css
  live-examples/html-examples/forms/css/legend.css
  live-examples/html-examples/inline-text-semantics/css/span.css
  live-examples/html-examples/inline-text-semantics/css/sub.css
  live-examples/html-examples/inline-text-semantics/css/sup.css
  live-examples/html-examples/inline-text-semantics/css/u.css
  live-examples/html-examples/input/css/button.css
  live-examples/html-examples/input/css/checkbox.css
  live-examples/html-examples/input/css/color.css
  live-examples/html-examples/input/css/date.css
  live-examples/html-examples/input/css/datetime-local.css
  live-examples/html-examples/input/css/email.css
  live-examples/html-examples/input/css/file.css
  live-examples/html-examples/input/css/image.css
  live-examples/html-examples/input/css/input.css
  live-examples/html-examples/input/css/month.css
  live-examples/html-examples/input/css/number.css
  live-examples/html-examples/input/css/password.css
  live-examples/html-examples/input/css/radio.css
  live-examples/html-examples/input/css/range.css
  live-examples/html-examples/input/css/reset.css
  live-examples/html-examples/input/css/tel.css
  live-examples/html-examples/input/css/text.css
  live-examples/html-examples/input/css/time.css
  live-examples/html-examples/input/css/url.css
  live-examples/html-examples/input/css/week.css
  live-examples/html-examples/table-content/css/caption.css
  live-examples/html-examples/text-content/css/dd.css
  live-examples/html-examples/text-content/css/dl.css
  live-examples/html-examples/text-content/css/dt.css
  live-examples/html-examples/text-content/css/ol.css
  media/fonts/DancingScript-Regular.ttf
  site.json
Labels: P1, bug

#1022 Add HTML example for <a> (issue #1014)
  live-examples/html-examples/inline-text-semantics/a.html
  live-examples/html-examples/inline-text-semantics/css/a.css
  live-examples/html-examples/inline-text-semantics/meta.json
  media/examples/external-link-alt-solid.svg
Labels: community, example needed

#1025 Change <select> examples to use “placeholder label option” pattern
  live-examples/html-examples/forms/option.html
  live-examples/html-examples/forms/select.html
Labels: community

#1031 Adds @tigt as contributor
  .all-contributorsrc
  README.md
Labels: community

#1028 Add a new line for markdown bullet list
  .github/config.yml
Labels: bug, community

#1032 chore(community): add @enguerran as contributor
  .all-contributorsrc
  README.md
Labels: community

#1029 Add example for <link>
  live-examples/html-examples/document-metadata/css/link.css
  live-examples/html-examples/document-metadata/link.html
  live-examples/html-examples/document-metadata/meta.json
  media/examples/link-element-example.css
Labels: community, example needed

#1030 Fix radio
  live-examples/html-examples/forms/css/fieldset.css
  live-examples/html-examples/forms/fieldset.html
  live-examples/html-examples/forms/meta.json
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/radio.html
Labels: bug

#1016 adding rb element example
  live-examples/html-examples/inline-text-semantics/css/rb.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/rb.html
Labels: example needed

#1046 adding class global attribute live example
  live-examples/html-examples/global-attributes/class.html
  live-examples/html-examples/global-attributes/css/class.css
  live-examples/html-examples/global-attributes/meta.json
Labels: example needed

#1047 adding contenteditable global attribute example
  live-examples/html-examples/global-attributes/contenteditable.html
  live-examples/html-examples/global-attributes/css/contenteditable.css
  live-examples/html-examples/global-attributes/meta.json
Labels: example needed

#1042 adding accesskey global attribute interactive example
  live-examples/html-examples/global-attributes/accesskey.html
  live-examples/html-examples/global-attributes/css/accesskey.css
  live-examples/html-examples/global-attributes/meta.json
Labels: example needed

#1051 Add @estelle as contributor
  .all-contributorsrc
  README.md
Labels: community

#1045 label for-attribute should reference id.
  live-examples/html-examples/forms/datalist.html
Labels: bug, community

#1052 chore(community): add @Row as a contributor
  .all-contributorsrc
  README.md
Labels: community

#1050 adding dir global attribute example
  live-examples/html-examples/global-attributes/css/dir.css
  live-examples/html-examples/global-attributes/dir.html
  live-examples/html-examples/global-attributes/meta.json
Labels: example needed

#1048 adding data-* global attribute interactive example
  live-examples/html-examples/global-attributes/css/data-*.css
  live-examples/html-examples/global-attributes/data-*.html
  live-examples/html-examples/global-attributes/meta.json
Labels: example needed
