Repository mdn/interactive-examples, pull requests merged in 2018-09, with the labels that each got.

#1120 Support prefixes
  CONTRIBUTING-CSS.md
  js/editor-libs/mce-utils.js
  live-examples/css-examples/fragmentation/box-decoration-break.css
  live-examples/css-examples/fragmentation/box-decoration-break.html
  live-examples/css-examples/text-decoration/text-emphasis.html
Labels: enhancement

#1132 chore(community): add @irenesmith as contributor
  .all-contributorsrc
  README.md
Labels: community

#1133 chore(community): add @meowwwls as contributor
  .all-contributorsrc
  README.md
Labels: community

#1134 chore(community): add @revelt as contributor
  .all-contributorsrc
  README.md
Labels: community

#1143 Editor config fix
  .editorconfig
Labels: bug

#1152 Add @Konrud as contributor
  .all-contributorsrc
  README.md
  package-lock.json
  package.json
Labels: community

#1153 Add @gene1woo as contributor
  .all-contributorsrc
  README.md
Labels: community

#1154 Add @justsml as contributor
  .all-contributorsrc
  README.md
Labels: community

#1155 Add @aeinbu as contributor
  .all-contributorsrc
  README.md
Labels: community

#1156 Add @eszjay as contributor
  .all-contributorsrc
  README.md
Labels: community

#1159 Bugfix 948422: increase colour contract of comments in code examples
  css/editor-libs/codemirror-override.css
Labels: a11y, community, enhancement

#1161 Add @ninjanails as contributor
  .all-contributorsrc
  README.md
Labels: community

#1088 Update <div> example to use cc0 image
  live-examples/html-examples/text-content/div.html
  media/examples/leopard.jpg
Labels: enhancement
