Repository mdn/interactive-examples, pull requests merged in 2018-08, with the labels that each got.

#1086 Use CC0 images in <picture> example
  live-examples/html-examples/embedded-content/picture.html
Labels: enhancement

#1104 chore(community): add @jpmedley as a contributor
  .all-contributorsrc
  README.md
Labels: community

#1091 Update cc0 figcaption
  live-examples/html-examples/text-content/css/figcaption.css
  live-examples/html-examples/text-content/figcaption.html
  media/cc0-images/Elephant_In_Silhouette_Closer--660x480.jpg
Labels: enhancement

#1092 Update main element example to use cc0 image
  live-examples/html-examples/text-content/css/main.css
  live-examples/html-examples/text-content/main.html
  media/cc0-images/Gecko--320x213.jpg
  media/cc0-images/Gecko--640x426.jpg
Labels: enhancement

#1100 Replace header image with a CC0 one
  live-examples/html-examples/content-sectioning/header.html
  media/examples/puppy-header-logo.jpg
Labels: bug

#1069 Added method for String[@@iterator]()
  live-examples/js-examples/string/meta.json
  live-examples/js-examples/string/string-iterator.html
Labels: example needed

#1071 Adding an example of String.split()
  live-examples/js-examples/string/meta.json
  live-examples/js-examples/string/string-split.html
Labels: example needed

#1112 Add window.ieConfig.origin for the target origin
  js/editor-libs/analytics.js
  js/editor-libs/events.js
  js/editor-libs/mce-utils.js
  js/editor-libs/perf.js
Labels: enhancement

#1070 Created an example for the String.raw() method
  live-examples/js-examples/string/meta.json
  live-examples/js-examples/string/string-raw.html
Labels: example needed
