Repository mdn/interactive-examples, pull requests merged in 2018-10, with the labels that each got.

#1087 Update <img> to use CC0 image
  live-examples/html-examples/image-and-multimedia/css/img.css
  live-examples/html-examples/image-and-multimedia/img.html
Labels: enhancement

#1101 Removed background image from optgroup
  live-examples/html-examples/forms/css/optgroup.css
  live-examples/html-examples/forms/optgroup.html
  media/examples/dino.jpg
Labels: bug

#1102 Remove background from option example
  live-examples/html-examples/forms/css/option.css
  live-examples/html-examples/forms/option.html
Labels: bug

#1099 Remove background from datalist example
  live-examples/html-examples/forms/css/datalist.css
  live-examples/html-examples/forms/datalist.html
  media/examples/ice-cream.jpg
Labels: bug

#1125 Clarifying Promise.resolve() Example
  live-examples/js-examples/promise/promise-resolve.html
Labels: community, example needed

#1080 Added an example for String.length
  live-examples/js-examples/string/meta.json
  live-examples/js-examples/string/string-length.html
Labels: example needed

#1078 Adding method for String.valueOf() method
  live-examples/js-examples/string/meta.json
  live-examples/js-examples/string/string-valueof.html
Labels: example needed

#1076 Adding an example for the String.toString() method
  live-examples/js-examples/string/meta.json
  live-examples/js-examples/string/string-tostring.html
Labels: example needed

#1180 Adds h1-h6 example
  live-examples/html-examples/content-sectioning/css/h1-h6.css
  live-examples/html-examples/content-sectioning/h1-h6.html
  live-examples/html-examples/content-sectioning/meta.json
Labels: community, example needed, hacktoberfest

#1183 chore(community): add @TremaineNeethling as contributor
  .all-contributorsrc
  README.md
Labels: community

#1195 chore(community) - Add @Flying-Toast as contributor
  .all-contributorsrc
  README.md
Labels: community

#1182 Js example output value changed
  live-examples/js-examples/object/object-entries.html
Labels: bug, community, hacktoberfest

#1189 Add "attribute-" prefix to HTML attribute examples.
  live-examples/html-examples/global-attributes/attribute-accesskey.html
  live-examples/html-examples/global-attributes/attribute-class.html
  live-examples/html-examples/global-attributes/attribute-contenteditable.html
  live-examples/html-examples/global-attributes/attribute-data.html
  live-examples/html-examples/global-attributes/attribute-dir.html
  live-examples/html-examples/global-attributes/attribute-hidden.html
  live-examples/html-examples/global-attributes/attribute-id.html
  live-examples/html-examples/global-attributes/attribute-lang.html
  live-examples/html-examples/global-attributes/attribute-spellcheck.html
  live-examples/html-examples/global-attributes/attribute-style.html
  live-examples/html-examples/global-attributes/attribute-tabindex.html
  live-examples/html-examples/global-attributes/attribute-title.html
  live-examples/html-examples/global-attributes/css/attribute-accesskey.css
  live-examples/html-examples/global-attributes/css/attribute-class.css
  live-examples/html-examples/global-attributes/css/attribute-contenteditable.css
  live-examples/html-examples/global-attributes/css/attribute-data.css
  live-examples/html-examples/global-attributes/css/attribute-hidden.css
  live-examples/html-examples/global-attributes/css/attribute-id.css
  live-examples/html-examples/global-attributes/css/attribute-lang.css
  live-examples/html-examples/global-attributes/css/attribute-spellcheck.css
  live-examples/html-examples/global-attributes/css/attribute-style.css
  live-examples/html-examples/global-attributes/css/attribute-tabindex.css
  live-examples/html-examples/global-attributes/css/attribute-title.css
  live-examples/html-examples/global-attributes/css/data-.css
  live-examples/html-examples/global-attributes/meta.json
Labels: community, documentation

#1203 chore(community) - Add @ShadowMitia as contributor
  .all-contributorsrc
  README.md
Labels: community

#1191 Fixup use consistent naming for filenames
  live-examples/html-examples/embedded-content/embed.html
  live-examples/html-examples/embedded-content/object.html
  live-examples/html-examples/embedded-content/picture.html
  live-examples/html-examples/embedded-content/source.html
  live-examples/html-examples/image-and-multimedia/img.html
  live-examples/html-examples/image-and-multimedia/track.html
  live-examples/html-examples/image-and-multimedia/video.html
  live-examples/html-examples/text-content/figcaption.html
  live-examples/html-examples/text-content/main.html
  live-examples/media/cc0-images/Birch_Trunks--1280x854.jpg
  live-examples/media/cc0-images/Birch_Trunks--640x427.jpg
  live-examples/media/cc0-images/Elephant_in_Silhouette--1280x854.jpg
  live-examples/media/cc0-images/Elephant_in_Silhouette--640x427.jpg
  live-examples/media/cc0-images/Gecko--640x426.jpg
  live-examples/media/cc0-images/Grapefruit_Slice--690x690.jpg
  live-examples/media/cc0-images/Grapefruit_Slices--1280x854.jpg
  live-examples/media/cc0-images/Grapefruit_Slices--640x427.jpg
  live-examples/media/cc0-images/Green_Landscape--1280x552.jpg
  live-examples/media/cc0-images/Green_Landscape--640x276.jpg
  live-examples/media/cc0-images/Painted_Hand--600x662.jpg
  live-examples/media/cc0-images/Painted_Hands--1280x854.jpg
  live-examples/media/cc0-images/Painted_Hands--640x427.jpg
  live-examples/media/cc0-images/Peacock--1280x776.jpg
  live-examples/media/cc0-images/Peacock--640x388.jpg
  live-examples/media/cc0-images/Pencils_and_Thumbtacks--1280x960.jpg
  live-examples/media/cc0-images/Pencils_and_Thumbtacks--640x480.jpg
  live-examples/media/cc0-images/Playing_Cards--1280x897.jpg
  live-examples/media/cc0-images/Playing_Cards--640x449.jpg
  live-examples/media/cc0-images/Sunset_Hummingbird--1280x854.jpg
  live-examples/media/cc0-images/Sunset_Hummingbird--640x427.jpg
  live-examples/media/cc0-images/Tiger--1280x1025.jpg
  live-examples/media/cc0-images/Tiger--640x513.jpg
  live-examples/media/cc0-images/Wave_and_Surfer--1280x699.jpg
  live-examples/media/cc0-images/Wave_and_Surfer--350x350.jpg
  live-examples/media/cc0-images/Wave_and_Surfer--640x350.jpg
  live-examples/media/cc0-images/Whiteboard--1280x854.jpg
  live-examples/media/cc0-images/Whiteboard--640x427.jpg
  live-examples/media/cc0-images/elephant-660-480.jpg
  live-examples/media/cc0-images/gecko-320-213.jpg
  live-examples/media/cc0-images/grapefruit-slice-332-332.jpg
  live-examples/media/cc0-images/painted-hand-298-332.jpg
  live-examples/media/cc0-images/surfer-240-200.jpg
  live-examples/media/examples/pdf-open-parameters.pdf
  live-examples/media/examples/stream-of-water-audioless.webm
  live-examples/media/examples/stream-of-water.mp4
  live-examples/media/examples/stream-of-water.vtt
  live-examples/media/examples/stream-of-water.webm
  package-lock.json
Labels: cleanup
