Repository mdn/interactive-examples, pull requests merged in 2018-06, with the labels that each got.

#960 Fix console util to support negative zero
  __tests__/console-utils.test.js
  js/editor-libs/console-utils.js
Labels: bug, community

#961 fix(tabbed-editor): Apply output class to output container
  __tests__/puppeteer-tabbed-editor.test.js
  css/tabbed-editor.css
  js/editor-libs/template-utils.js
  package-lock.json
  package.json
  tmpl/live-tabbed-tmpl.html
Labels: P1, bug

#965 Issue#837 html entity workaround
  CONTRIBUTING-HTML.md
  live-examples/html-examples/inline-text-semantics/wbr.html
Labels: documentation, enhancement

#958 Add rtc example.
  live-examples/html-examples/inline-text-semantics/css/rtc.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/rtc.html
Labels: cf:high, community, example needed

#962 Issue#693 add sizing util classes tabbed editor
  .eslintrc.js
  CONTRIBUTING-HTML.md
  __tests__/puppeteer-tabbed-editor.test.js
  css/tabbed-editor.css
  js/editor-libs/template-utils.js
  js/editor.js
  lib/pageBuilderUtils.js
  lib/tabbedPageBuilder.js
  live-examples/html-examples/content-sectioning/meta.json
  live-examples/html-examples/demarcating-edits/meta.json
  live-examples/html-examples/document-metadata/meta.json
  live-examples/html-examples/embedded-content/meta.json
  live-examples/html-examples/forms/meta.json
  live-examples/html-examples/image-and-multimedia/meta.json
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/interactive-elements/meta.json
  live-examples/html-examples/table-content/meta.json
  live-examples/html-examples/text-content/meta.json
  tmpl/live-tabbed-tmpl.html
Labels: P1, enhancement

#959 Add ruby example.
  live-examples/html-examples/inline-text-semantics/css/ruby.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/ruby.html
Labels: cf:high, community, example needed

#967 fix(performance): send loadEventEnd to parent via postMessage
  .prettierrc
  js/editable-css.js
  js/editable-js.js
  js/editor-libs/events.js
  js/editor.js
Labels: P1, enhancement, performance

#971 fix(editor): change height of tabbed-taller
  css/tabbed-editor.css
Labels: P1, bug, cf:high

#914 [HTML Examples] Text Content ~ main
  live-examples/html-examples/text-content/css/main.css
  live-examples/html-examples/text-content/main.html
  live-examples/html-examples/text-content/meta.json
Labels: example needed

#984 Bumps the timeout inside readystatechange to 300ms of the js editor
  js/editable-js.js
Labels: P1, performance

#991 Remove old metrics and cleanup
  js/editor-libs/analytics.js
  js/editor-libs/events.js
  js/editor-libs/mce-utils.js
  package-lock.json
Labels: P1, enhancement

#977 fix(perf): adds and inlines perf.js ~ Fix issue #976
  js/editor-libs/perf.js
  lib/pageBuilder.js
  lib/pageBuilderUtils.js
  tmpl/live-css-tmpl.html
  tmpl/live-html-tmpl.html
  tmpl/live-js-tmpl.html
  tmpl/live-tabbed-tmpl.html
Labels: P1, enhancement, performance

#1001 fix(performance): send post to kuma for custom ie-load-event-end metric
  js/editable-css.js
  js/editable-js.js
  js/editor-libs/mce-utils.js
  js/editor.js
Labels: enhancement, performance

#1002 chore(community): add @Arkangus as contributor
  .all-contributorsrc
  README.md
Labels: community
