Repository mdn/interactive-examples, pull requests merged in 2018-05, with the labels that each got.

#843 Reinstate caption in meta.json
  live-examples/html-examples/table-content/meta.json
Labels: P1, bug, in sprint

#838 Add <input type="datetime-local"> example
  live-examples/html-examples/input/css/datetime-local.css
  live-examples/html-examples/input/datetime-local.html
  live-examples/html-examples/input/meta.json
Labels: P1, in sprint

#852 Add input-file example
  live-examples/html-examples/input/css/file.css
  live-examples/html-examples/input/file.html
  live-examples/html-examples/input/meta.json
Labels: P1, in sprint

#842 Add picture example.
  live-examples/html-examples/embedded-content/css/picture.css
  live-examples/html-examples/embedded-content/meta.json
  live-examples/html-examples/embedded-content/picture.html
  media/examples/picture-narrow.png
  media/examples/picture-wide.png
Labels: P1, in sprint

#840 Add input type=email example
  live-examples/html-examples/input/css/email.css
  live-examples/html-examples/input/email.html
  live-examples/html-examples/input/meta.json
Labels: P1, in sprint

#848 adding thead, tbody, and tfoot examples
  live-examples/html-examples/table-content/css/tbody.css
  live-examples/html-examples/table-content/css/tfoot.css
  live-examples/html-examples/table-content/css/thead.css
  live-examples/html-examples/table-content/meta.json
  live-examples/html-examples/table-content/tbody.html
  live-examples/html-examples/table-content/tfoot.html
  live-examples/html-examples/table-content/thead.html
Labels: P1, in sprint

#716 Adds sanity puppeteer test for CSS editor
  __tests__/puppeteer-css-editor.test.js
Labels: P1, testing

#717 test: add sanity pupeteer tests for tabbed editor
  __tests__/puppeteer-tabbed-editor.test.js
Labels: P1, testing

#869 chore: add @sheeeng as contributor
  .all-contributorsrc
  README.md
Labels: community

#847 Add <ins> example
  live-examples/html-examples/demarcating-edits/css/ins.css
  live-examples/html-examples/demarcating-edits/ins.html
  live-examples/html-examples/demarcating-edits/meta.json
Labels: P1, community, in sprint

#839 Add <dd> example
  live-examples/html-examples/text-content/css/dd.css
  live-examples/html-examples/text-content/dd.html
  live-examples/html-examples/text-content/meta.json
Labels: P1, in sprint

#871 fix: run tests on different port than dev server
  CONTRIBUTING.md
  __tests__/puppeteer-css-editor.test.js
  __tests__/puppeteer-js-editor.test.js
  __tests__/puppeteer-tabbed-editor.test.js
  jest-puppeteer.config.js
  package.json
Labels: enhancement, in sprint, tooling

#865 Add html input month
  live-examples/html-examples/input/css/month.css
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/month.html
Labels: P1, in sprint

#878 Add html input range
  live-examples/html-examples/input/css/range.css
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/range.html
Labels: P1, in sprint

#866 Add html input number
  live-examples/html-examples/input/css/number.css
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/number.html
Labels: P1, in sprint

#889 chore: add @tbazin as contributor
  .all-contributorsrc
  README.md
Labels: community

#882 Add <span> example
  live-examples/html-examples/inline-text-semantics/css/span.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/span.html
Labels: P1, in sprint

#863 Add embed example.
  live-examples/html-examples/embedded-content/css/embed.css
  live-examples/html-examples/embedded-content/embed.html
  live-examples/html-examples/embedded-content/meta.json
  media/examples/stream_of_water.webm
  media/examples/stream_of_water_audioless.webm
Labels: P1, community, in sprint

#888 Add interactive example for <section>
  live-examples/html-examples/content-sectioning/css/section.css
  live-examples/html-examples/content-sectioning/meta.json
  live-examples/html-examples/content-sectioning/section.html
Labels: P1, in sprint

#884 Add <p> example
  live-examples/html-examples/text-content/css/p.css
  live-examples/html-examples/text-content/meta.json
  live-examples/html-examples/text-content/p.html
Labels: P1, in sprint

#883 Add <hr> example
  live-examples/html-examples/text-content/css/hr.css
  live-examples/html-examples/text-content/hr.html
  live-examples/html-examples/text-content/meta.json
Labels: P1, in sprint

#877 Replace <br> with <div> in input examples
  live-examples/html-examples/input/checkbox.html
  live-examples/html-examples/input/color.html
  live-examples/html-examples/input/date.html
  live-examples/html-examples/input/datetime-local.html
  live-examples/html-examples/input/file.html
Labels: P1, in sprint

#867 Add html input password
  live-examples/html-examples/input/css/password.css
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/password.html
Labels: P1, in sprint

#874 Add <wbr> example
  live-examples/html-examples/inline-text-semantics/css/wbr.css
  live-examples/html-examples/inline-text-semantics/meta.json
  live-examples/html-examples/inline-text-semantics/wbr.html
Labels: P1, in sprint

#894 Issue#860 add polyfill for shadow dom
  .eslintrc.js
  js/editor.js
  js/lib/webcomponents-hi-sd-ce.js
  site.json
Labels: P1, enhancement, in sprint

#828 [issue #767] [HTML Examples] Inline text semantics ~ br
  live-examples/html-examples/inline-text-semantics/br.html
  live-examples/html-examples/inline-text-semantics/css/br.css
  live-examples/html-examples/inline-text-semantics/meta.json
Labels: P1, in sprint

#891 Add Input ~ <input type="button">
  live-examples/html-examples/input/button.html
  live-examples/html-examples/input/css/button.css
  live-examples/html-examples/input/meta.json
Labels: P1, community, in sprint

#910 chore(contributors): Adds @nnupoor as contributor
  .all-contributorsrc
  README.md
Labels: community

#898 Add html input tel
  live-examples/html-examples/input/css/tel.css
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/tel.html
Labels: P1, example needed

#899 Add html input text
  live-examples/html-examples/input/css/text.css
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/text.html
Labels: P1, example needed

#900 Add time input example
  live-examples/html-examples/input/css/time.css
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/time.html
Labels: P1, example needed

#892 Add Input ~ input example
  live-examples/html-examples/input/css/input.css
  live-examples/html-examples/input/input.html
  live-examples/html-examples/input/meta.json
Labels: P1, community, in sprint

#912 fix(tests): fix failing css example test
  __tests__/puppeteer-css-editor.test.js
  package-lock.json
  package.json
Labels: bug, testing

#906 Update <blockquote> example
  live-examples/html-examples/text-content/blockquote.html
  live-examples/html-examples/text-content/css/blockquote.css
  live-examples/html-examples/text-content/meta.json
Labels: P1, example needed

#904 Add <nav> example
  live-examples/html-examples/content-sectioning/css/nav.css
  live-examples/html-examples/content-sectioning/meta.json
  live-examples/html-examples/content-sectioning/nav.html
Labels: P1, example needed

#897 Add html input search
  live-examples/html-examples/input/css/search.css
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/search.html
Labels: P1

#901 Add html input url
  live-examples/html-examples/input/css/url.css
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/url.html
Labels: P1, example needed

#902 Add html input week
  live-examples/html-examples/input/css/week.css
  live-examples/html-examples/input/meta.json
  live-examples/html-examples/input/week.html
Labels: P1, example needed

#922 Add String trim examples
  live-examples/js-examples/string/meta.json
  live-examples/js-examples/string/string-trim.html
  live-examples/js-examples/string/string-trimend.html
  live-examples/js-examples/string/string-trimstart.html
Labels: example needed

#924 Add HTML example for <details>
  live-examples/html-examples/interactive-elements/css/details.css
  live-examples/html-examples/interactive-elements/details.html
  live-examples/html-examples/interactive-elements/meta.json
Labels: community, example needed

#926 Add HTML example for <summary>
  live-examples/html-examples/interactive-elements/css/summary.css
  live-examples/html-examples/interactive-elements/meta.json
  live-examples/html-examples/interactive-elements/summary.html
Labels: community, example needed

#932 chore(community): add @stephanmax as contributor
  .all-contributorsrc
  README.md
Labels: community

#933 chore(community): add @Regaddi as contributor
  .all-contributorsrc
  README.md
Labels: community

#930 Add HTML example for <audio>
  live-examples/html-examples/image-and-multimedia/audio.html
Labels: community, enhancement

#931 Add <map> example
  live-examples/html-examples/image-and-multimedia/css/map.css
  live-examples/html-examples/image-and-multimedia/map.html
  live-examples/html-examples/image-and-multimedia/meta.json
  media/examples/mdn-info2.png
Labels: community, example needed

#920 Add <area> example
  live-examples/html-examples/image-and-multimedia/area.html
  live-examples/html-examples/image-and-multimedia/css/area.css
  live-examples/html-examples/image-and-multimedia/meta.json
  media/examples/mdn-info.png
Labels: community, example needed

#923 Add img example.
  live-examples/html-examples/image-and-multimedia/css/img.css
  live-examples/html-examples/image-and-multimedia/img.html
  live-examples/html-examples/image-and-multimedia/meta.json
Labels: community, example needed

#927 fix(tabbed-editor): issue #860, isolate CSS to output
  .eslintrc.js
  .gitignore
  js/editor-libs/shadow-output.js
  js/editor-libs/template-utils.js
  js/editor.js
  js/lib/webcomponents-hi-sd-ce.js
  js/lib/webcomponents/webcomponents-bundle.js
  package-lock.json
  site.json
Labels: P1, enhancement, release blocker

#919 adding font-optical-sizing example
  live-examples/css-examples/fonts/font-optical-sizing.css
  live-examples/css-examples/fonts/font-optical-sizing.html
  live-examples/css-examples/fonts/meta.json
  media/fonts/AmstelvarAlpha-VF.ttf
Labels: example needed

#937 Add object-keys.html
  live-examples/js-examples/object/meta.json
  live-examples/js-examples/object/object-keys.html
Labels: community, example needed

#951 chore(community): add @elharony as contributor
  .all-contributorsrc
  README.md
Labels: community

#947 Fix font optical sizing
  live-examples/css-examples/fonts/font-optical-sizing.html
Labels: bug, example needed

#948 Font variation settings
  live-examples/css-examples/fonts/font-variation-settings.css
  live-examples/css-examples/fonts/font-variation-settings.html
  live-examples/css-examples/fonts/meta.json
Labels: example needed

#941 Implemented example for <figcaption> tag
  live-examples/html-examples/text-content/css/figcaption.css
  live-examples/html-examples/text-content/figcaption.html
  live-examples/html-examples/text-content/meta.json
Labels: community, example needed

#934 chore(docs): update README with maintainers and good first issues
  CONTRIBUTING.md
  README.md
Labels: documentation
