Repository mdn/interactive-examples, pull requests merged in 2022-04, with the labels that each got.

#1916 Add fieldset/legend to the checkbox example
  live-examples/html-examples/input/checkbox.html
Labels: community

#2075 Explicitly set interactive example output bg to #fff
  live-examples/css-examples/backgrounds-and-borders/border-style.css
Labels: bug, community

#2099 ruby-position
  live-examples/css-examples/text/meta.json
  live-examples/css-examples/text/ruby-position.css
  live-examples/css-examples/text/ruby-position.html
Labels: community

#1704 Use a fieldset within the input/radio example
  live-examples/html-examples/input/radio.html
Labels: a11y, community

#2107 chore:cleanup ~ remove all contributors
  .all-contributorsrc
  README.md
Labels: chore

#2066 appearance
  live-examples/css-examples/basic-user-interface/appearance.html
Labels: community

#2093 Adds matrix & matrix3d functions
  live-examples/css-examples/transforms/function-matrix.html
  live-examples/css-examples/transforms/function-matrix3d.html
  live-examples/css-examples/transforms/meta.json
Labels: Content:CSS, community
