Repository mdn/interactive-examples, pull requests merged in 2022-12, with the labels that each got.

#2345 Add JS example: Symbol.prototype.valueOf()
  live-examples/js-examples/symbol/meta.json
  live-examples/js-examples/symbol/symbol-prototype-valueof.js
Labels: Content:JS

#2343 Add JS example: Symbol.asyncIterator
  live-examples/js-examples/symbol/meta.json
  live-examples/js-examples/symbol/symbol-asynciterator.js
Labels: Content:JS

#2341 Add JS GeneratorFunction examples
  live-examples/js-examples/functionasterisk/async-functionasterisk-function.js
  live-examples/js-examples/functionasterisk/functionasterisk-function.js
  live-examples/js-examples/functionasterisk/meta.json
Labels: Content:JS

#2122 layer at-rule
  live-examples/css-examples/cascading-and-inheritance/at-rule-layer.css
  live-examples/css-examples/cascading-and-inheritance/at-rule-layer.html
  live-examples/css-examples/cascading-and-inheritance/meta.json
Labels: Content:CSS, community

#2334 Add JS Object.setPrototypeOf
  live-examples/js-examples/object/meta.json
  live-examples/js-examples/object/object-setprototypeof.js
Labels: Content:JS

#2324 Add JS Object.is()
  live-examples/js-examples/object/meta.json
  live-examples/js-examples/object/object-is.js
Labels: Content:JS

#2382 chore: adds pull request template
  .github/PULL_REQUEST_TEMPLATE
Labels: chore

#2381 chore: add repo template files
  REVIEWING.md
  SECURITY.md
Labels: chore

#2380 chore: add idle and welcome-bot workflows
  .github/workflows/idle.yml
  .github/workflows/welcome-bot.yml
Labels: chore

#2391 Fix: correct return type for function
  live-examples/wat-examples/statements/select.wat
Labels: Content:WASM
