Repository mdn/interactive-examples, pull requests merged in 2022-06, with the labels that each got.

#1717 Added Intl.NumberFormat.formatToParts() example
  live-examples/js-examples/intl/intl-numberformat-prototype-formattoparts.js
  live-examples/js-examples/intl/meta.json
Labels: Content:WebAPI, community

#1726 Remove reduce function from restparameters example
  live-examples/js-examples/functions/functions-restparameters.js
Labels: Content:JS, community

#1898 add example for transform: perspective(none);
  live-examples/css-examples/transforms/function-perspective.html
Labels: Content:CSS, community

#2111 defaultTab info
  CONTRIBUTING-HTML.md
Labels: documentation

#2096 Pseudo-elements after & before
  live-examples/css-examples/pseudo-element/after.css
  live-examples/css-examples/pseudo-element/after.html
  live-examples/css-examples/pseudo-element/before.css
  live-examples/css-examples/pseudo-element/before.html
  live-examples/css-examples/pseudo-element/meta.json
Labels: enhancement, Content:CSS, community

#2020 Fix Wasm trunc example
  live-examples/wat-examples/numeric/trunc.wat
Labels: community, Content:WASM

#2060 Removed redundant guard clause
  live-examples/js-examples/functions/functions-getter.js
Labels: Content:JS, community

#1963 Update expressions-right-shift.js
  live-examples/js-examples/expressions/expressions-right-shift-assignment.js
  live-examples/js-examples/expressions/expressions-right-shift.js
Labels: Content:JS, community

#2119 Functions circle, ellipse, inset, polygon, path
  live-examples/css-examples/values-and-units/function-circle.html
  live-examples/css-examples/values-and-units/function-ellipse.html
  live-examples/css-examples/values-and-units/function-inset.html
  live-examples/css-examples/values-and-units/function-path.html
  live-examples/css-examples/values-and-units/function-polygon.html
  live-examples/css-examples/values-and-units/meta.json
Labels: community

#2129 font-variant-east-asian
  live-examples/css-examples/fonts/font-variant-east-asian.css
  live-examples/css-examples/fonts/font-variant-east-asian.html
  live-examples/css-examples/fonts/meta.json
Labels: enhancement, community

#2193 chore: fixup package.json
  package.json
  yarn.lock
Labels: dependencies, chore
