Repository mdn/interactive-examples, pull requests merged in 2022-05, with the labels that each got.

#1930 fix #633 data-property formatting
  live-examples/css-examples/backgrounds-and-borders/background-attachment.html
  live-examples/css-examples/backgrounds-and-borders/background-clip.html
  live-examples/css-examples/backgrounds-and-borders/background-color.html
  live-examples/css-examples/backgrounds-and-borders/background-image.html
  live-examples/css-examples/backgrounds-and-borders/background-origin.html
  live-examples/css-examples/backgrounds-and-borders/background-position-x.html
  live-examples/css-examples/backgrounds-and-borders/background-position-y.html
  live-examples/css-examples/backgrounds-and-borders/background-position.html
  live-examples/css-examples/backgrounds-and-borders/background-repeat.html
  live-examples/css-examples/backgrounds-and-borders/background-size.html
  live-examples/css-examples/backgrounds-and-borders/border-bottom-style.html
  live-examples/css-examples/backgrounds-and-borders/border-image-outset.html
  live-examples/css-examples/backgrounds-and-borders/border-image-repeat.html
  live-examples/css-examples/backgrounds-and-borders/border-image-slice.html
  live-examples/css-examples/backgrounds-and-borders/border-image-source.html
  live-examples/css-examples/backgrounds-and-borders/border-image-width.html
  live-examples/css-examples/backgrounds-and-borders/border-image.html
  live-examples/css-examples/backgrounds-and-borders/border-left-style.html
  live-examples/css-examples/backgrounds-and-borders/border-right-style.html
  live-examples/css-examples/backgrounds-and-borders/border-style.html
  live-examples/css-examples/backgrounds-and-borders/border-top-style.html
  live-examples/css-examples/backgrounds-and-borders/box-shadow.html
  live-examples/css-examples/basic-box-model/margin-bottom.html
  live-examples/css-examples/basic-box-model/margin-left.html
  live-examples/css-examples/basic-box-model/margin-right.html
  live-examples/css-examples/basic-box-model/margin-top.html
  live-examples/css-examples/basic-user-interface/box-sizing.html
  live-examples/css-examples/basic-user-interface/text-overflow.html
  live-examples/css-examples/fonts/font-style.html
  live-examples/css-examples/images/object-fit.html
  live-examples/css-examples/positioned-layout/z-index.html
  live-examples/css-examples/text-decoration/text-decoration-color.html
  live-examples/css-examples/text-decoration/text-decoration-line.html
  live-examples/css-examples/text-decoration/text-decoration-skip-ink.html
  live-examples/css-examples/text-decoration/text-decoration-style.html
  live-examples/css-examples/text-decoration/text-decoration-thickness.html
  live-examples/css-examples/text-decoration/text-decoration.html
  live-examples/css-examples/text-decoration/text-shadow.html
  live-examples/css-examples/text-decoration/text-underline-offset.html
  live-examples/css-examples/text/letter-spacing.html
  live-examples/css-examples/text/tab-size.html
  live-examples/css-examples/text/text-align.html
  live-examples/css-examples/text/text-transform.html
  live-examples/css-examples/text/white-space.html
  live-examples/css-examples/text/word-break.html
  live-examples/css-examples/text/word-spacing.html
  live-examples/css-examples/transforms/transform-origin.html
  live-examples/css-examples/transitions/line-height.html
Labels: chore, community

#2136 chore:automation ~ add release please
  .github/workflows/publish-release.yml
Labels: chore

#2074 docs: Change prefixed property example in meta-docs
  CONTRIBUTING-CSS.md
Labels: documentation, community

#1705 fix: Clarify string-endswith examples
  live-examples/js-examples/string/string-endswith.js
Labels: Content:JS, community

#1454 Improve readability and consistency of array-reduce examples
  live-examples/js-examples/array/array-reduce-right.js
Labels: Content:JS, community

#2139 fix: only run deploy action if labeled release
  .github/workflows/deploy.yml
Labels: chore

#2140 fix: only run deploy action if labeled release
  .github/workflows/deploy.yml
Labels: bug, chore

#1897 feat: add logical properties example for float
  live-examples/css-examples/basic-box-model/float.html
Labels: Content:CSS, community

#2150 fix: remove expression syntax from if conditional
  .github/workflows/publish-release.yml
Labels: chore

#2152 fix: Update publish-release.yml
  .github/workflows/publish-release.yml
Labels: chore

#2151 chore(main): release 1.0.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#2123 Update Date.setTime()
  live-examples/js-examples/date/date-settime.js
Labels: enhancement, community

#2155 chore(main): release 1.0.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#2161 workflows: add on-demand prod deploy workflow
  .github/workflows/prod-deploy.yml
Labels: chore
