Repository mdn/interactive-examples, pull requests merged in 2023-08, with the labels that each got.

#2536 feat: add JavaScript to code snippet
  live-examples/html-examples/input/url.html
Labels: Content:HTML

#2404 Add examples for FinalizationRegistry
  live-examples/js-examples/finalizationregistry/finalizationregistry-prototype-unregister.js
  live-examples/js-examples/finalizationregistry/finalizationregistry.js
  live-examples/js-examples/finalizationregistry/meta.json
Labels: Content:JS

#2403 Add examples for WeakRef
  live-examples/js-examples/weakref/meta.json
  live-examples/js-examples/weakref/weakref-constructor.js
  live-examples/js-examples/weakref/weakref-prototype-deref.js
  live-examples/js-examples/weakref/weakref.js
Labels: Content:JS

#2214 feat(html): Add example of `<output>`
  live-examples/html-examples/interactive-elements/css/output.css
  live-examples/html-examples/interactive-elements/js/output.js
  live-examples/html-examples/interactive-elements/meta.json
  live-examples/html-examples/interactive-elements/output.html
Labels: Content:HTML

#2462 docs: Add `tabs` property to the documentation
  contributing/html-examples.md
Labels: idle

#2351 add hyphenate-limit-chars example
  live-examples/css-examples/text/hyphenate-limit-chars.css
  live-examples/css-examples/text/hyphenate-limit-chars.html
  live-examples/css-examples/text/meta.json
Labels: Content:CSS

#2253 feat: showcase basic array functionality
  live-examples/js-examples/array/array.js
  live-examples/js-examples/array/meta.json
Labels: Content:JS

#2220 feat(html): Add example of `draggable` attribute
  live-examples/html-examples/global-attributes/attribute-draggable.html
  live-examples/html-examples/global-attributes/css/attribute-draggable.css
  live-examples/html-examples/global-attributes/js/attribute-draggable.js
  live-examples/html-examples/global-attributes/meta.json
Labels: Content:HTML

#2212 feat(html): Add example of `<dialog>`
  live-examples/html-examples/interactive-elements/css/dialog.css
  live-examples/html-examples/interactive-elements/dialog.html
  live-examples/html-examples/interactive-elements/js/dialog.js
  live-examples/html-examples/interactive-elements/meta.json
Labels: Content:HTML

#1971 Fix nesting depth in Array.prototype.flat example
  live-examples/js-examples/array/array-flat.js
Labels: Content:JS, community

#2589 Add TA.p[@@iterator] example; consistent file names for @@iterator & supportedValuesOf
  live-examples/js-examples/array/meta.json
  live-examples/js-examples/expressions/expressions-nullish-coalescing-assignment.js
  live-examples/js-examples/expressions/meta.json
  live-examples/js-examples/intl/meta.json
  live-examples/js-examples/intl/segments-prototype-@@iterator.js
  live-examples/js-examples/intl/segments-prototype-containing.js
  live-examples/js-examples/string/meta.json
  live-examples/js-examples/typedarray/meta.json
  live-examples/js-examples/typedarray/typedarray-iterator.js
Labels: Content:JS

#2015 Map.groupBy() interactive example
  live-examples/js-examples/map/map-groupby.js
  live-examples/js-examples/map/meta.json
Labels: Content:JS, community

#2089 feat(css): Add example of `@counter-style` and all of its descriptors
  .husky/pre-commit
  .prettierrc.json
  live-examples/css-examples/@counter-style/additive-symbols.css
  live-examples/css-examples/@counter-style/counter-list-negative.html
  live-examples/css-examples/@counter-style/counter-list.html
  live-examples/css-examples/@counter-style/counter-style.css
  live-examples/css-examples/@counter-style/fallback.css
  live-examples/css-examples/@counter-style/meta.json
  live-examples/css-examples/@counter-style/negative.css
  live-examples/css-examples/@counter-style/pad.css
  live-examples/css-examples/@counter-style/prefix.css
  live-examples/css-examples/@counter-style/range.css
  live-examples/css-examples/@counter-style/suffix.css
  live-examples/css-examples/@counter-style/symbols.css
  live-examples/css-examples/@counter-style/system.css
Labels: Content:CSS

#2411 Add an example for BigInt64Array()
  live-examples/js-examples/typedarray/meta.json
  live-examples/js-examples/typedarray/typedarray-bigint64.js
Labels: Content:JS
